### ISSUE TITLE
Safari: SyntaxError: Invalid regular expression: invalid group specifier name

### ISSUE THREAD

**Issue by baptistebriel** [mikehwagz/choozy#3]
Hey! I'm getting an error using `choozy` on Safari 13.0.4, see screenshot:

![Screen Shot 2020-01-13 at 4 29 45 PM](https://user-images.githubusercontent.com/2464663/72268429-18bc4100-3622-11ea-9f3e-5f879e698405.png)

Seems like some RegExp issues... Only breaks on Safari, it's fine on Chrome.
Do you have any ideas? Cheers!

**Comment by mikehwagz** [comment]
Doh! The library currently does not even use RegExp haha. Must have accidentally published the dist folder from another branch... Thanks for bringing to my attention!

Should be resolved in 0.0.6!

**Comment by baptistebriel** [comment]
Thanks a lot! 🖤
